[config]

[templates.gtk3]
input_path = '~/.config/noctalia/templates/gtk-3.0.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/noctalia/templates/gtk-4.0.css'
output_path = '~/.config/gtk-4.0/theme/colors.css'

[templates.qt5ct]
input_path = '~/.config/noctalia/templates/qt.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = '~/.config/noctalia/templates/qt.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.niri]
input_path = '~/.config/noctalia/templates/niri.kdl'
output_path = '~/.config/niri/theme/colors.kdl'

[templates.btop]
input_path = '~/.config/noctalia/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.micro]
input_path = '~/.config/noctalia/templates/micro.micro'
output_path = '~/.config/micro/colorschemes/matugen.micro'