format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "bold green"
format = '[$path]($style)[$read_only]($read_only_style) '

[character]
error_symbol = "[λ](bold red)"
success_symbol = "[λ](bold green)"

[cmd_duration]
style = "bold yellow"

[git_branch]
style = "bold purple"
format = '\[[$symbol$branch(:$remote_branch)]($style)\]'
symbol=''

[git_commit]
style = "bold cyan"
format = '\[[󰜘$hash]($style)\] '
commit_hash_length = 8
only_detached=false

[git_status]
style = "bold red"

[hostname]
style = "bold purple"

[username]
format = '[$user]($style) on '
style_user = "bold cyan"